apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-management-server
  labels:
    app: risk-management-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-management-server
  template:
    metadata:
      labels:
        app: risk-management-server
    spec:
      containers:
        - env:
            - name: ACTIVEMQ_HOST
              value: http://ad824f8bf704542a695eeafac692ea41-1750005900.eu-central-1.elb.amazonaws.com
            - name: ACTIVEMQ_PORT
              value: "61613"
          image: 613825731605.dkr.ecr.eu-central-1.amazonaws.com/lakeside:risk-management-server-latest
          imagePullPolicy: Always
          name: risk-management-server
          ports:
            - containerPort: 50051
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: risk-management-server
spec:
  selector:
    app: risk-management-server
  ports:
    - name: "50051"
      port: 50051
      targetPort: 50051
  type: LoadBalancer
