apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-backend
  labels:
    app: customer-management-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-management-backend
  template:
    metadata:
      labels:
        app: customer-management-backend
    spec:
      containers:
        - env:
            - name: CUSTOMERCORE_BASEURL
              value: http://###URL_CUSTOMER_CORE###:8110
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: http://###URL_SPRING_BOOT_ADMIN###:9000
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL
              value: http://###URL_CUSTOMER_MANAGEMENT_BACKEND###:8100
          image: ###URL_ECR###:customer-management-backend-latest
          imagePullPolicy: Always
          name: customer-management-backend
          ports:
            - containerPort: 8100
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: customer-management-backend
spec:
  selector:
    app: customer-management-backend
  ports:
    - name: "8100"
      port: 8100
      targetPort: 8100
  type: LoadBalancer
