apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-self-service-backend
  labels:
    app: customer-self-service-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-self-service-backend
  template:
    metadata:
      labels:
        app: customer-self-service-backend
    spec:
      containers:
        - env:
            - name: CUSTOMERCORE_BASEURL
              value: http://###URL_CUSTOMER_CORE###:8110
            - name: POLICYMANAGEMENT_TCPBROKERBINDADDRESS
              value: tcp://###URL_POLICY_MANAGEMENT_BACKEND###:61616
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: http://###URL_SPRING_BOOT_ADMIN_CLIENT###:9000
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL
              value: http://###URL_CUSTOMER_SELF_SERVICE_BACKEND###:8080
          image: ###URL_ECR###:customer-self-service-backend-latest
          imagePullPolicy: Always
          name: customer-self-service-backend
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: customer-self-service-backend
spec:
  selector:
    app: customer-self-service-backend
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
