apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-management-frontend
  labels:
    app: policy-management-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-management-frontend
  template:
    metadata:
      labels:
        app: policy-management-frontend
    spec:
      containers:
        - env:
            - name: VUE_APP_POLICY_MANAGEMENT_BACKEND
              value: http://a0053ede0e7384b40a84df5293efe962-252133721.eu-central-1.elb.amazonaws.com:8090
          image: ###URL_ECR###:policy-management-frontend-latest
          imagePullPolicy: Always
          name: policy-management-frontend
          ports:
            - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: policy-management-frontend
spec:
  selector:
    app: policy-management-frontend
  ports:
    - name: "3010"
      port: 3010
      targetPort: 80
  type: LoadBalancer
