apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-self-service-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-self-service-backend
  template:
    metadata:
      labels:
        app: customer-self-service-backend
    spec:
      containers:
      - name: customer-self-service-backend
        image: 613825731605.dkr.ecr.eu-central-1.amazonaws.com/lakeside:customer-self-service-backend-latest
        ports:
        - containerPort: 8080
