apiVersion: v1
kind: Service
metadata:
  name: customer-self-service-frontend
spec:
  type: LoadBalancer
  selector:
    app: customer-self-service-frontend
  ports:
  - port: 80
    targetPort: 3000
