apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-management-frontend
  template:
    metadata:
      labels:
        app: customer-management-frontend
    spec:
      containers:
      - name: customer-management-frontend
        image: 613825731605.dkr.ecr.eu-central-1.amazonaws.com/lakeside:customer-management-frontend-latest
        ports:
        - containerPort: 3020
