apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-self-service-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-self-service-frontend
  template:
    metadata:
      labels:
        app: customer-self-service-frontend
    spec:
      containers:
      - name: customer-self-service-frontend
        image: 613825731605.dkr.ecr.eu-central-1.amazonaws.com/lakeside:customer-self-service-frontend-latest
        ports:
        - containerPort: 3000
